ogham_data = [
    {
        "code_point": 5760,
        "ogham_character": " ",
        "english_analog": " ",
        "unicode_category": "Space Separator",
        "ogham_name": "space mark",
        "aicme": 'Punctuation',
        "aicme_position": 1,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5761,
        "ogham_character": "ᚁ",
        "english_analog": "b",
        "unicode_category": "Other Letter",
        "ogham_name": "beith",
        "aicme": "Beithe",
        "aicme_position": 1,
        "tree": "birch",
        "start_date": "Dec 24",
        "end_date": "Jan 20",
        "meanings": [
            "new beginnings",
            "change",
            "release",
            "rebirth",
            "cleansing",
            "hope",
            "pioneering energy"
        ]
    },
    {
        "code_point": 5762,
        "ogham_character": "ᚂ",
        "english_analog": "l",
        "unicode_category": "Other Letter",
        "ogham_name": "luis",
        "aicme": "Beithe",
        "aicme_position": 2,
        "tree": "rowan",
        "start_date": "Jan 21",
        "end_date": "Feb 17",
        "meanings": [
            "insight",
            "protection",
            "blessings",
            "psychic intuition",
            "fiery energy",
            "perserverance",
            "humility"
        ]
    },
    {
        "code_point": 5763,
        "ogham_character": "ᚃ",
        "english_analog": "f, w, v",
        "unicode_category": "Other Letter",
        "ogham_name": "fearn",
        "aicme": "Beithe",
        "aicme_position": 3,
        "tree": "alder",
        "start_date": "Mar 18",
        "end_date": "Apr 14",
        "meanings": [
            "confidence",
            "encouragement",
            "shield",
            "honorable conduct",
            "discrimination",
            "bad luck",
            "secrecy"
        ]
    },
    {
        "code_point": 5764,
        "ogham_character": "ᚄ",
        "english_analog": "s",
        "unicode_category": "Other Letter",
        "ogham_name": "sail",
        "aicme": "Beithe",
        "aicme_position": 4,
        "tree": "willow",
        "start_date": "Apr 15",
        "end_date": "May 12",
        "meanings": [
            "knowledge",
            "spiritual growth",
            "moon cycles",
            "women's cycles",
            "April",
            "harmony",
            "balance",
            "grief",
            "dreams",
            "emotion"
        ]
    },
    {
        "code_point": 5765,
        "ogham_character": "ᚅ",
        "english_analog": "n",
        "unicode_category": "Other Letter",
        "ogham_name": "nion",
        "aicme": "Beithe",
        "aicme_position": 5,
        "tree": "ash",
        "start_date": "Feb 18",
        "end_date": "Mar 17",
        "meanings": [
            "sacred",
            "transitions",
            "creativity",
            "connections",
            "courage",
            "focus",
            "solar energy",
            "vitality"
        ]
    },
    {
        "code_point": 5766,
        "ogham_character": "ᚆ",
        "english_analog": "h",
        "unicode_category": "Other Letter",
        "ogham_name": "uath",
        "aicme": "hÚatha",
        "aicme_position": 1,
        "tree": "hawthorn",
        "start_date": "May 13",
        "end_date": "Jun 9",
        "meanings": [
            "cleansing",
            "protection",
            "defense",
            "fertility",
            "masculinity",
            "love",
            "happiness",
            "gentleness",
            "beauty"
        ]
    },
    {
        "code_point": 5767,
        "ogham_character": "ᚇ",
        "english_analog": "d",
        "unicode_category": "Other Letter",
        "ogham_name": "dair",
        "aicme": "hÚatha",
        "aicme_position": 2,
        "tree": "oak",
        "start_date": "Jun 10",
        "end_date": "Jul 7",
        "meanings": [
            "strength",
            "resiliance",
            "self-confidence",
            "leadership",
            "trust",
            "soverieignty",
            "loyalty"
        ]
    },
    {
        "code_point": 5768,
        "ogham_character": "ᚈ",
        "english_analog": "t",
        "unicode_category": "Other Letter",
        "ogham_name": "tinne",
        "aicme": "hÚatha",
        "aicme_position": 3,
        "tree": "holly",
        "start_date": "Jul 8",
        "end_date": "Aug 4",
        "meanings": [
            "immordtality",
            "unity",
            "courage",
            "stability of home",
            "empathy",
            "boundaries",
            "protection"
        ]
    },
    {
        "code_point": 5769,
        "ogham_character": "ᚉ",
        "english_analog": "c, k",
        "unicode_category": "Other Letter",
        "ogham_name": "coll",
        "aicme": "hÚatha",
        "aicme_position": 4,
        "tree": "hazel",
        "start_date": "Jul 8",
        "end_date": "Aug 4",
        "meanings": [
            "wisdom",
            "creativity",
            "knowledge",
            "divination",
            "sacred wells",
            "communication"
        ]
    },
    {
        "code_point": 5770,
        "ogham_character": "ᚊ",
        "english_analog": "q",
        "unicode_category": "Other Letter",
        "ogham_name": "ceirt",
        "aicme": "hÚatha",
        "aicme_position": 5,
        "tree": "apple",
        "start_date": "Aug 5",
        "end_date": "Sep 1",
        "meanings": [
            "love",
            "faithfulness",
            "rebirth",
            "prosperity",
            "fertility",
            "attraction",
            "faerie realms",
            "youthful enerty"
        ]
    },
    {
        "code_point": 5771,
        "ogham_character": "ᚋ",
        "english_analog": "m",
        "unicode_category": "Other Letter",
        "ogham_name": "muin",
        "aicme": "Muine",
        "aicme_position": 1,
        "tree": "vine",
        "start_date": "Sep 2",
        "end_date": "Sept 29",
        "meanings": [
            "prophecy",
            "truth speaking",
            "inward journey",
            "life lessons learned",
            "harvest",
            "wealth",
            "cycles"
        ]
    },
    {
        "code_point": 5772,
        "ogham_character": "ᚌ",
        "english_analog": "g",
        "unicode_category": "Other Letter",
        "ogham_name": "gort",
        "aicme": "Muine",
        "aicme_position": 2,
        "tree": "ivy",
        "start_date": "Sep 30",
        "end_date": "Oct 27",
        "meanings": [
            "growth",
            "wildness",
            "women's good fortune",
            "mystical development",
            "protective magic",
            "good fortune",
            "steadfastness",
            "friendship",
            "connections",
            "support"
        ]
    },
    {
        "code_point": 5773,
        "ogham_character": "ᚍ",
        "english_analog": "ng",
        "unicode_category": "Other Letter",
        "ogham_name": "nGeadal",
        "aicme": "Muine",
        "aicme_position": 3,
        "tree": "reed",
        "start_date": "Oct 28",
        "end_date": "Nov 24",
        "meanings": [
            "music",
            "direct action",
            "finding purpose",
            "healing",
            "health",
            "social gathering",
            "responsibility",
            "ancestral skills",
            "order to chaos"
        ]
    },
    {
        "code_point": 5774,
        "ogham_character": "ᚎ",
        "english_analog": "st, z",
        "unicode_category": "Other Letter",
        "ogham_name": "straif",
        "aicme": "Muine",
        "aicme_position": 4,
        "tree": "blackthorn",
        "start_date": "Oct 28",
        "end_date": "Nov 24",
        "meanings": [
            "authority",
            "control",
            "triumph",
            "power",
            "anger",
            "magical protection",
            "banishing negativity"
        ]
    },
    {
        "code_point": 5775,
        "ogham_character": "ᚏ",
        "english_analog": "r",
        "unicode_category": "Other Letter",
        "ogham_name": "ruis",
        "aicme": "Muine",
        "aicme_position": 5,
        "tree": "elder",
        "start_date": "Nov 25",
        "end_date": "Dec 23",
        "meanings": [
            "endings",
            "maturity",
            "wisdom",
            "polarity",
            "equilibrium",
            "purification",
            "initiation to dark mysteries",
            "underworld goddess work"
        ]
    },
    {
        "code_point": 5776,
        "ogham_character": "ᚐ",
        "english_analog": "a",
        "unicode_category": "Other Letter",
        "ogham_name": "ailm",
        "aicme": "Ailme",
        "aicme_position": 1,
        "tree": "elm",
        "start_date": None,
        "end_date": None,
        "meanings": [
            "clarity",
            "alignment",
            "perspective",
            "calm",
            "contemplation",
            "meditation"
        ]
    },
    {
        "code_point": 5777,
        "ogham_character": "ᚑ",
        "english_analog": "o",
        "unicode_category": "Other Letter",
        "ogham_name": "onn",
        "aicme": "Ailme",
        "aicme_position": 2,
        "tree": "gorse",
        "start_date": None,
        "end_date": None,
        "meanings": [
            "long-term planning",
            "perserverance",
            "hope",
            "sexuality",
            "financial abundance",
            "solar energy",
            "life force"
        ]
    },
    {
        "code_point": 5778,
        "ogham_character": "ᚒ",
        "english_analog": "u",
        "unicode_category": "Other Letter",
        "ogham_name": "ur",
        "aicme": "Ailme",
        "aicme_position": 3,
        "tree": "heather",
        "start_date": None,
        "end_date": None,
        "meanings": [
            "passion",
            "generosity",
            "healing",
            "positivity",
            "love",
            "goddess blessings"
        ]
    },
    {
        "code_point": 5779,
        "ogham_character": "ᚓ",
        "english_analog": "e",
        "unicode_category": "Other Letter",
        "ogham_name": "eadhadh",
        "aicme": "Ailme",
        "aicme_position": 4,
        "tree": "aspen",
        "start_date": None,
        "end_date": None,
        "meanings": [
            "endurance",
            "courage",
            "strong will",
            "success",
            "spiritual protection"
        ]
    },
    {
        "code_point": 5780,
        "ogham_character": "ᚔ",
        "english_analog": "i, y",
        "unicode_category": "Other Letter",
        "ogham_name": "iodhadh",
        "aicme": "Ailme",
        "aicme_position": 5,
        "tree": "yew",
        "start_date": None,
        "end_date": None,
        "meanings": [
            "death",
            "endings",
            "rebirth",
            "ancestral wisdom",
            "reincarnation",
            "other world journeying"
        ]
    },
    {
        "code_point": 5781,
        "ogham_character": "ᚕ",
        "english_analog": "e, x",
        "unicode_category": "Other Letter",
        "ogham_name": "eabhadh",
        "aicme": "Forfeda",
        "aicme_position": 1,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5782,
        "ogham_character": "ᚖ",
        "english_analog": "o",
        "unicode_category": "Other Letter",
        "ogham_name": "or",
        "aicme": "Forfeda",
        "aicme_position": 2,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5783,
        "ogham_character": "ᚗ",
        "english_analog": "u",
        "unicode_category": "Other Letter",
        "ogham_name": "uilleann",
        "aicme": "Forfeda",
        "aicme_position": 3,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5784,
        "ogham_character": "ᚘ",
        "english_analog": "i",
        "unicode_category": "Other Letter",
        "ogham_name": "ifin",
        "aicme": "Forfeda",
        "aicme_position": 4,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5785,
        "ogham_character": "ᚙ",
        "english_analog": "e",
        "unicode_category": "Other Letter",
        "ogham_name": "eamhancholl",
        "aicme": "Forfeda",
        "aicme_position": 5,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5786,
        "ogham_character": "ᚚ",
        "english_analog": "p",
        "unicode_category": "Other Letter",
        "ogham_name": "peith",
        "aicme": "Forfeda",
        "aicme_position": 6,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5787,
        "ogham_character": "᚛",
        "english_analog": None,
        "unicode_category": "Open Punctuation",
        "ogham_name": "feather mark",
        "aicme": 'Punctuation',
        "aicme_position": 2,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5788,
        "ogham_character": "᚜",
        "english_analog": None,
        "unicode_category": "Close Punctuation",
        "ogham_name": "reversed feather mark",
        "aicme": 'Punctuation',
        "aicme_position": 3,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    }
]

kennings = [
  {
    "ogham_letter": "ᚁ",
    "english_letter": "B",
    "ogham_name": "Beithe",
    "meaning": "Birch",
    "Morainn_Irish": "féochos foltchain",
    "Morainn_English": "withered foot with fine hair",
    "Oengus_Irish": "glaisem cnis",
    "Oengus_English": "greyest of skin",
    "Cuchulain_Irish": "maise malach",
    "Cuchulain_English": "beauty of the eyebrow"
  },
  {
    "ogham_letter": "ᚂ",
    "english_letter": "L",
    "ogham_name": "Luis",
    "meaning": "Flame or Herb",
    "Morainn_Irish": "lí súla",
    "Morainn_English": "lustre of the eye",
    "Oengus_Irish": "carae cethrae",
    "Oengus_English": "friend of cattle",
    "Cuchulain_Irish": "lúth cethrae",
    "Cuchulain_English": "sustenance of cattle"
  },
  {
    "ogham_letter": "ᚃ",
    "english_letter": "F",
    "ogham_name": "Fern",
    "meaning": "Alder",
    "Morainn_Irish": "airenach fían",
    "Morainn_English": "vanguard of warriors",
    "Oengus_Irish": "comét lachta",
    "Oengus_English": "milk container",
    "Cuchulain_Irish": "dín cridi",
    "Cuchulain_English": "protection of the heart"
  },
  {
    "ogham_letter": "ᚄ",
    "english_letter": "S",
    "ogham_name": "Sail",
    "meaning": "Willow",
    "Morainn_Irish": "lí ambi",
    "Morainn_English": "pallor of a lifeless one",
    "Oengus_Irish": "lúth bech",
    "Oengus_English": "sustenance of bees",
    "Cuchulain_Irish": "tosach mela",
    "Cuchulain_English": "beginning of honey"
  },
  {
    "ogham_letter": "ᚅ",
    "english_letter": "N",
    "ogham_name": "Nin",
    "meaning": "Branch-fork",
    "Morainn_Irish": "costud síde",
    "Morainn_English": "establishing of peace",
    "Oengus_Irish": "bág ban",
    "Oengus_English": "boast of women",
    "Cuchulain_Irish": "bág maise",
    "Cuchulain_English": "boast of beauty"
  },
  {
    "ogham_letter": "ᚆ",
    "english_letter": "H",
    "ogham_name": "Úath",
    "meaning": "Fear",
    "Morainn_Irish": "condál cúan",
    "Morainn_English": "assembly of packs of hounds",
    "Oengus_Irish": "bánad gnúise",
    "Oengus_English": "blanching of faces",
    "Cuchulain_Irish": "ansam aidche",
    "Cuchulain_English": "most difficult at night"
  },
  {
    "ogham_letter": "ᚇ",
    "english_letter": "D",
    "ogham_name": "Dair",
    "meaning": "Oak",
    "Morainn_Irish": "ardam dosae",
    "Morainn_English": "highest tree",
    "Oengus_Irish": "grés soír",
    "Oengus_English": "handicraft of a craftsman",
    "Cuchulain_Irish": "slechtam soíre",
    "Cuchulain_English": "most carved of craftsmanship"
  },
  {
    "ogham_letter": "ᚈ",
    "english_letter": "T",
    "ogham_name": "Tinne",
    "meaning": "Iron Bar",
    "Morainn_Irish": "trian roith",
    "Morainn_English": "one of three parts of a wheel",
    "Oengus_Irish": "smiur gúaile",
    "Oengus_English": "marrow of (char)coal",
    "Cuchulain_Irish": "trian n-airm",
    "Cuchulain_English": "one of three parts of a weapon"
  },
  {
    "ogham_letter": "ᚉ",
    "english_letter": "C",
    "ogham_name": "Coll",
    "meaning": "Hazel",
    "Morainn_Irish": "caíniu fedaib",
    "Morainn_English": "fairest tree",
    "Oengus_Irish": "carae blóesc",
    "Oengus_English": "friend of nutshells",
    "Cuchulain_Irish": "milsem fedo",
    "Cuchulain_English": "sweetest tree"
  },
  {
    "ogham_letter": "ᚊ",
    "english_letter": "Q",
    "ogham_name": "Cert",
    "meaning": "Bush or Rag",
    "Morainn_Irish": "clithar baiscill",
    "Morainn_English": "shelter of a [lunatic?]",
    "Oengus_Irish": "bríg anduini",
    "Oengus_English": "substance of an insignificant person",
    "Cuchulain_Irish": "dígu fethail",
    "Cuchulain_English": "dregs of clothing"
  },
  {
    "ogham_letter": "ᚋ",
    "english_letter": "M",
    "ogham_name": "Muin",
    "meaning": "Neck, Ruse/Trick or Love",
    "Morainn_Irish": "tressam fedmae",
    "Morainn_English": "strongest in exertion",
    "Oengus_Irish": "árusc n-airlig",
    "Oengus_English": "proverb of slaughter",
    "Cuchulain_Irish": "conar gotha",
    "Cuchulain_English": "path of the voice"
  },
  {
    "ogham_letter": "ᚌ",
    "english_letter": "G",
    "ogham_name": "Gort",
    "meaning": "Field",
    "Morainn_Irish": "milsiu féraib",
    "Morainn_English": "sweetest grass",
    "Oengus_Irish": "ined erc",
    "Oengus_English": "suitable place for cows",
    "Cuchulain_Irish": "sásad ile",
    "Cuchulain_English": "sating of multitudes"
  },
  {
    "ogham_letter": "ᚍ",
    "english_letter": "GG",
    "ogham_name": "Gétal",
    "meaning": "Slaying",
    "Morainn_Irish": "lúth lego",
    "Morainn_English": "sustenance of a leech",
    "Oengus_Irish": "étiud midach",
    "Oengus_English": "raiment of physicians",
    "Cuchulain_Irish": "tosach n-échto",
    "Cuchulain_English": "beginning of slaying"
  },
  {
    "ogham_letter": "ᚎ",
    "english_letter": "Z",
    "ogham_name": "Straif",
    "meaning": "Sulphur",
    "Morainn_Irish": "tressam rúamnai",
    "Morainn_English": "strongest reddening (dye)",
    "Oengus_Irish": "mórad rún",
    "Oengus_English": "increase of secrets",
    "Cuchulain_Irish": "saigid nél",
    "Cuchulain_English": "seeking of clouds"
  },
  {
    "ogham_letter": "ᚏ",
    "english_letter": "R",
    "ogham_name": "Ruis",
    "meaning": "Red",
    "Morainn_Irish": "tindem rucci",
    "Morainn_English": "most intense blushing",
    "Oengus_Irish": "rúamnae drech",
    "Oengus_English": "reddening of faces",
    "Cuchulain_Irish": "bruth fergae",
    "Cuchulain_English": "glow of anger"
  },
  {
    "ogham_letter": "ᚐ",
    "english_letter": "A",
    "ogham_name": "Ailm",
    "meaning": "Pine?",
    "Morainn_Irish": "ardam íachta",
    "Morainn_English": "loudest groan",
    "Oengus_Irish": "tosach frecrai",
    "Oengus_English": "beginning of an answer",
    "Cuchulain_Irish": "tosach garmae",
    "Cuchulain_English": "beginning of calling"
  },
  {
    "ogham_letter": "ᚑ",
    "english_letter": "O",
    "ogham_name": "Onn",
    "meaning": "Ash-tree",
    "Morainn_Irish": "congnaid ech",
    "Morainn_English": "wounder of horses",
    "Oengus_Irish": "féthem soíre",
    "Oengus_English": "smoothest of craftsmanship",
    "Cuchulain_Irish": "lúth fían",
    "Cuchulain_English": "[equipment] of warrior bands"
  },
  {
    "ogham_letter": "ᚒ",
    "english_letter": "U",
    "ogham_name": "Úr",
    "meaning": "Earth",
    "Morainn_Irish": "úaraib adbaib",
    "Morainn_English": "in cold dwellings",
    "Oengus_Irish": "sílad cland",
    "Oengus_English": "propagation of plants",
    "Cuchulain_Irish": "forbbaid ambí",
    "Cuchulain_English": "shroud of a lifeless one"
  },
  {
    "ogham_letter": "ᚓ",
    "english_letter": "E",
    "ogham_name": "Edad",
    "meaning": "Aspen (modern Irish Eabhadh, Eadha)",
    "Morainn_Irish": "érgnaid fid",
    "Morainn_English": "discerning tree",
    "Oengus_Irish": "commaín carat",
    "Oengus_English": "exchange of friends",
    "Cuchulain_Irish": "bráthair bethi",
    "Cuchulain_English": "brother of birch"
  },
  {
    "ogham_letter": "ᚔ",
    "english_letter": "I",
    "ogham_name": "Idad",
    "meaning": "Yew-tree?",
    "Morainn_Irish": "sinem fedo",
    "Morainn_English": "oldest tree",
    "Oengus_Irish": "caínem sen",
    "Oengus_English": "fairest of the ancients",
    "Cuchulain_Irish": "lúth lobair",
    "Cuchulain_English": "energy of an infirm person"
  },
  {
    "ogham_letter": "ᚕ",
    "english_letter": "EA",
    "ogham_name": "Ébad",
    "meaning": "Unknown",
    "Morainn_Irish": "snámchaín feda",
    "Morainn_English": "fair-swimming letter",
    "Oengus_Irish": "cosc lobair",
    "Oengus_English": "[admonishing?] of an infirm person",
    "Cuchulain_Irish": "caínem éco",
    "Cuchulain_English": "fairest fish"
  },
  {
    "ogham_letter": "ᚖ",
    "english_letter": "OI",
    "ogham_name": "Óir",
    "meaning": "Gold",
    "Morainn_Irish": "sruithem aicde",
    "Morainn_English": "most venerable substance",
    "Oengus_Irish": "lí crotha",
    "Oengus_English": "splendour of form",
    "Cuchulain_Irish": None,
    "Cuchulain_English": None
  },
  {
    "ogham_letter": "ᚗ",
    "english_letter": "UI",
    "ogham_name": "Uillenn",
    "meaning": "Elbow",
    "Morainn_Irish": "túthmar fid",
    "Morainn_English": "fragrant tree",
    "Oengus_Irish": "cubat oll",
    "Oengus_English": "great elbow/cubit",
    "Cuchulain_Irish": None,
    "Cuchulain_English": None
  },
  {
    "ogham_letter": "ᚘ",
    "english_letter": "IO",
    "ogham_name": "Iphín",
    "meaning": "Spine/thorn?",
    "Morainn_Irish": "milsem fedo",
    "Morainn_English": "sweetest tree",
    "Oengus_Irish": "amram mlais",
    "Oengus_English": "most wonderful taste",
    "Cuchulain_Irish": None,
    "Cuchulain_English": None
  },
  {
    "ogham_letter": "ᚙ",
    "english_letter": "AE",
    "ogham_name": "Emancholl",
    "meaning": "Twin-of-hazel",
    "Morainn_Irish": "lúad sáethaig",
    "Morainn_English": "groan of a sick person",
    "Oengus_Irish": "mol galraig",
    "Oengus_English": "groan of a sick person",
    "Cuchulain_Irish": None,
    "Cuchulain_English": None
  }
]