ogham_data = [
    {
        "code_point": 5760,
        "ogham_character": " ",
        "english_analog": " ",
        "unicode_category": "Space Separator",
        "ogham_name": "space mark",
        "aicme": 'Punctuation',
        "aicme_position": 1,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5761,
        "ogham_character": "ᚁ",
        "english_analog": "b",
        "unicode_category": "Other Letter",
        "ogham_name": "beith",
        "aicme": "Beithe",
        "aicme_position": 1,
        "tree": "birch",
        "start_date": "Dec 24",
        "end_date": "Jan 20",
        "meanings": [
            "new beginnings",
            "change",
            "release",
            "rebirth",
            "cleansing",
            "hope",
            "pioneering energy"
        ]
    },
    {
        "code_point": 5762,
        "ogham_character": "ᚂ",
        "english_analog": "l",
        "unicode_category": "Other Letter",
        "ogham_name": "luis",
        "aicme": "Beithe",
        "aicme_position": 2,
        "tree": "rowan",
        "start_date": "Jan 21",
        "end_date": "Feb 17",
        "meanings": [
            "insight",
            "protection",
            "blessings",
            "psychic intuition",
            "fiery energy",
            "perserverance",
            "humility"
        ]
    },
    {
        "code_point": 5763,
        "ogham_character": "ᚃ",
        "english_analog": "f, w, v",
        "unicode_category": "Other Letter",
        "ogham_name": "fearn",
        "aicme": "Beithe",
        "aicme_position": 3,
        "tree": "alder",
        "start_date": "Mar 18",
        "end_date": "Apr 14",
        "meanings": [
            "confidence",
            "encouragement",
            "shield",
            "honorable conduct",
            "discrimination",
            "bad luck",
            "secrecy"
        ]
    },
    {
        "code_point": 5764,
        "ogham_character": "ᚄ",
        "english_analog": "s",
        "unicode_category": "Other Letter",
        "ogham_name": "sail",
        "aicme": "Beithe",
        "aicme_position": 4,
        "tree": "willow",
        "start_date": "Apr 15",
        "end_date": "May 12",
        "meanings": [
            "knowledge",
            "spiritual growth",
            "moon cycles",
            "women's cycles",
            "April",
            "harmony",
            "balance",
            "grief",
            "dreams",
            "emotion"
        ]
    },
    {
        "code_point": 5765,
        "ogham_character": "ᚅ",
        "english_analog": "n",
        "unicode_category": "Other Letter",
        "ogham_name": "nion",
        "aicme": "Beithe",
        "aicme_position": 5,
        "tree": "ash",
        "start_date": "Feb 18",
        "end_date": "Mar 17",
        "meanings": [
            "sacred",
            "transitions",
            "creativity",
            "connections",
            "courage",
            "focus",
            "solar energy",
            "vitality"
        ]
    },
    {
        "code_point": 5766,
        "ogham_character": "ᚆ",
        "english_analog": "h",
        "unicode_category": "Other Letter",
        "ogham_name": "uath",
        "aicme": "hÚatha",
        "aicme_position": 1,
        "tree": "hawthorn",
        "start_date": "May 13",
        "end_date": "Jun 9",
        "meanings": [
            "cleansing",
            "protection",
            "defense",
            "fertility",
            "masculinity",
            "love",
            "happiness",
            "gentleness",
            "beauty"
        ]
    },
    {
        "code_point": 5767,
        "ogham_character": "ᚇ",
        "english_analog": "d",
        "unicode_category": "Other Letter",
        "ogham_name": "dair",
        "aicme": "hÚatha",
        "aicme_position": 2,
        "tree": "oak",
        "start_date": "Jun 10",
        "end_date": "Jul 7",
        "meanings": [
            "strength",
            "resiliance",
            "self-confidence",
            "leadership",
            "trust",
            "soverieignty",
            "loyalty"
        ]
    },
    {
        "code_point": 5768,
        "ogham_character": "ᚈ",
        "english_analog": "t",
        "unicode_category": "Other Letter",
        "ogham_name": "tinne",
        "aicme": "hÚatha",
        "aicme_position": 3,
        "tree": "holly",
        "start_date": "Jul 8",
        "end_date": "Aug 4",
        "meanings": [
            "immordtality",
            "unity",
            "courage",
            "stability of home",
            "empathy",
            "boundaries",
            "protection"
        ]
    },
    {
        "code_point": 5769,
        "ogham_character": "ᚉ",
        "english_analog": "c, k",
        "unicode_category": "Other Letter",
        "ogham_name": "coll",
        "aicme": "hÚatha",
        "aicme_position": 4,
        "tree": "hazel",
        "start_date": "Jul 8",
        "end_date": "Aug 4",
        "meanings": [
            "wisdom",
            "creativity",
            "knowledge",
            "divination",
            "sacred wells",
            "communication"
        ]
    },
    {
        "code_point": 5770,
        "ogham_character": "ᚊ",
        "english_analog": "q",
        "unicode_category": "Other Letter",
        "ogham_name": "ceirt",
        "aicme": "hÚatha",
        "aicme_position": 5,
        "tree": "apple",
        "start_date": "Aug 5",
        "end_date": "Sep 1",
        "meanings": [
            "love",
            "faithfulness",
            "rebirth",
            "prosperity",
            "fertility",
            "attraction",
            "faerie realms",
            "youthful enerty"
        ]
    },
    {
        "code_point": 5771,
        "ogham_character": "ᚋ",
        "english_analog": "m",
        "unicode_category": "Other Letter",
        "ogham_name": "muin",
        "aicme": "Muine",
        "aicme_position": 1,
        "tree": "vine",
        "start_date": "Sep 2",
        "end_date": "Sept 29",
        "meanings": [
            "prophecy",
            "truth speaking",
            "inward journey",
            "life lessons learned",
            "harvest",
            "wealth",
            "cycles"
        ]
    },
    {
        "code_point": 5772,
        "ogham_character": "ᚌ",
        "english_analog": "g",
        "unicode_category": "Other Letter",
        "ogham_name": "gort",
        "aicme": "Muine",
        "aicme_position": 2,
        "tree": "ivy",
        "start_date": "Sep 30",
        "end_date": "Oct 27",
        "meanings": [
            "growth",
            "wildness",
            "women's good fortune",
            "mystical development",
            "protective magic",
            "good fortune",
            "steadfastness",
            "friendship",
            "connections",
            "support"
        ]
    },
    {
        "code_point": 5773,
        "ogham_character": "ᚍ",
        "english_analog": "ng",
        "unicode_category": "Other Letter",
        "ogham_name": "nGeadal",
        "aicme": "Muine",
        "aicme_position": 3,
        "tree": "reed",
        "start_date": "Oct 28",
        "end_date": "Nov 24",
        "meanings": [
            "music",
            "direct action",
            "finding purpose",
            "healing",
            "health",
            "social gathering",
            "responsibility",
            "ancestral skills",
            "order to chaos"
        ]
    },
    {
        "code_point": 5774,
        "ogham_character": "ᚎ",
        "english_analog": "st, z",
        "unicode_category": "Other Letter",
        "ogham_name": "straif",
        "aicme": "Muine",
        "aicme_position": 4,
        "tree": "blackthorn",
        "start_date": "Oct 28",
        "end_date": "Nov 24",
        "meanings": [
            "authority",
            "control",
            "triumph",
            "power",
            "anger",
            "magical protection",
            "banishing negativity"
        ]
    },
    {
        "code_point": 5775,
        "ogham_character": "ᚏ",
        "english_analog": "r",
        "unicode_category": "Other Letter",
        "ogham_name": "ruis",
        "aicme": "Muine",
        "aicme_position": 5,
        "tree": "elder",
        "start_date": "Nov 25",
        "end_date": "Dec 23",
        "meanings": [
            "endings",
            "maturity",
            "wisdom",
            "polarity",
            "equilibrium",
            "purification",
            "initiation to dark mysteries",
            "underworld goddess work"
        ]
    },
    {
        "code_point": 5776,
        "ogham_character": "ᚐ",
        "english_analog": "a",
        "unicode_category": "Other Letter",
        "ogham_name": "ailm",
        "aicme": "Ailme",
        "aicme_position": 1,
        "tree": "elm",
        "start_date": None,
        "end_date": None,
        "meanings": [
            "clarity",
            "alignment",
            "perspective",
            "calm",
            "contemplation",
            "meditation"
        ]
    },
    {
        "code_point": 5777,
        "ogham_character": "ᚑ",
        "english_analog": "o",
        "unicode_category": "Other Letter",
        "ogham_name": "onn",
        "aicme": "Ailme",
        "aicme_position": 2,
        "tree": "gorse",
        "start_date": None,
        "end_date": None,
        "meanings": [
            "long-term planning",
            "perserverance",
            "hope",
            "sexuality",
            "financial abundance",
            "solar energy",
            "life force"
        ]
    },
    {
        "code_point": 5778,
        "ogham_character": "ᚒ",
        "english_analog": "u",
        "unicode_category": "Other Letter",
        "ogham_name": "ur",
        "aicme": "Ailme",
        "aicme_position": 3,
        "tree": "heather",
        "start_date": None,
        "end_date": None,
        "meanings": [
            "passion",
            "generosity",
            "healing",
            "positivity",
            "love",
            "goddess blessings"
        ]
    },
    {
        "code_point": 5779,
        "ogham_character": "ᚓ",
        "english_analog": "e",
        "unicode_category": "Other Letter",
        "ogham_name": "eadhadh",
        "aicme": "Ailme",
        "aicme_position": 4,
        "tree": "aspen",
        "start_date": None,
        "end_date": None,
        "meanings": [
            "endurance",
            "courage",
            "strong will",
            "success",
            "spiritual protection"
        ]
    },
    {
        "code_point": 5780,
        "ogham_character": "ᚔ",
        "english_analog": "i, y",
        "unicode_category": "Other Letter",
        "ogham_name": "iodhadh",
        "aicme": "Ailme",
        "aicme_position": 5,
        "tree": "yew",
        "start_date": None,
        "end_date": None,
        "meanings": [
            "death",
            "endings",
            "rebirth",
            "ancestral wisdom",
            "reincarnation",
            "other world journeying"
        ]
    },
    {
        "code_point": 5781,
        "ogham_character": "ᚕ",
        "english_analog": "e, x",
        "unicode_category": "Other Letter",
        "ogham_name": "eabhadh",
        "aicme": "Forfeda",
        "aicme_position": 1,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5782,
        "ogham_character": "ᚖ",
        "english_analog": "o",
        "unicode_category": "Other Letter",
        "ogham_name": "or",
        "aicme": "Forfeda",
        "aicme_position": 2,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5783,
        "ogham_character": "ᚗ",
        "english_analog": "u",
        "unicode_category": "Other Letter",
        "ogham_name": "uilleann",
        "aicme": "Forfeda",
        "aicme_position": 3,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5784,
        "ogham_character": "ᚘ",
        "english_analog": "i",
        "unicode_category": "Other Letter",
        "ogham_name": "ifin",
        "aicme": "Forfeda",
        "aicme_position": 4,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5785,
        "ogham_character": "ᚙ",
        "english_analog": "e",
        "unicode_category": "Other Letter",
        "ogham_name": "eamhancholl",
        "aicme": "Forfeda",
        "aicme_position": 5,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5786,
        "ogham_character": "ᚚ",
        "english_analog": "p",
        "unicode_category": "Other Letter",
        "ogham_name": "peith",
        "aicme": "Forfeda",
        "aicme_position": 6,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5787,
        "ogham_character": "᚛",
        "english_analog": None,
        "unicode_category": "Open Punctuation",
        "ogham_name": "feather mark",
        "aicme": 'Punctuation',
        "aicme_position": 2,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    },
    {
        "code_point": 5788,
        "ogham_character": "᚜",
        "english_analog": None,
        "unicode_category": "Close Punctuation",
        "ogham_name": "reversed feather mark",
        "aicme": 'Punctuation',
        "aicme_position": 3,
        "tree": None,
        "start_date": None,
        "end_date": None,
        "meanings": None
    }
]